# Load dependencies

In [5]:
import tensorflow as tf
import os
import pandas as pd
import numpy as np
# from tensorflow.compact.v1 import ConfigProto

In [6]:
# np.

In [7]:
# import tensorflow as tf
# print("Num of GPUs available: ", len(tf.test.gpu_device_name()))


In [8]:
gpus=tf.config.experimental.list_physical_devices("GPU")
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu,True)
gpus

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [9]:
cd D:/Course/DrivenData Project

D:\Course\DrivenData Project


In [10]:
print(pd.__version__)

1.5.1


# Import Files


In [11]:
data_dir='Dataset'
t=os.path.join(data_dir,'train_features')
p=os.listdir(os.path.join(data_dir,'train_features'))
len(p)

16488

In [12]:
df=pd.read_csv(os.path.join(data_dir,'train_features.csv'))
df

id                     filepath   site
0      ZJ000000  train_features/ZJ000000.jpg  S0120
1      ZJ000001  train_features/ZJ000001.jpg  S0069
2      ZJ000002  train_features/ZJ000002.jpg  S0009
3      ZJ000003  train_features/ZJ000003.jpg  S0008
4      ZJ000004  train_features/ZJ000004.jpg  S0036
...         ...                          ...    ...
16483  ZJ016483  train_features/ZJ016483.jpg  S0093
16484  ZJ016484  train_features/ZJ016484.jpg  S0043
16485  ZJ016485  train_features/ZJ016485.jpg  S0089
16486  ZJ016486  train_features/ZJ016486.jpg  S0095
16487  ZJ016487  train_features/ZJ016487.jpg  S0021

[16488 rows x 3 columns]

In [13]:
train_labels = pd.read_csv(os.path.join(data_dir,'train_labels.csv'))
classes = train_labels.columns[1:]
t_labels = train_labels.iloc[:, 1:]
train_y = np.array([np.argmax(t_labels.iloc[i, :]) for i in range(t_labels.shape[0])])
l=list(train_y)
train_labels


id  antelope_duiker  bird  blank  civet_genet  hog  leopard  \
0      ZJ000000              0.0   1.0    0.0          0.0  0.0      0.0   
1      ZJ000001              0.0   0.0    0.0          0.0  0.0      0.0   
2      ZJ000002              0.0   1.0    0.0          0.0  0.0      0.0   
3      ZJ000003              0.0   0.0    0.0          0.0  0.0      0.0   
4      ZJ000004              0.0   0.0    0.0          0.0  0.0      1.0   
...         ...              ...   ...    ...          ...  ...      ...   
16483  ZJ016483              0.0   0.0    1.0          0.0  0.0      0.0   
16484  ZJ016484              0.0   0.0    0.0          0.0  0.0      1.0   
16485  ZJ016485              0.0   0.0    0.0          1.0  0.0      0.0   
16486  ZJ016486              0.0   1.0    0.0          0.0  0.0      0.0   
16487  ZJ016487              0.0   0.0    0.0          1.0  0.0      0.0   

       monkey_prosimian  rodent  
0                   0.0     0.0  
1                   1.0     0.0  
2                   0.0     0.0  
3                   1.0     0.0  
4                   0.0     0.0  
...                 ...     ...  
16483               0.0     0.0  
16484               0.0     0.0  
16485               0.0     0.0  
16486               0.0     0.0  
16487               0.0     0.0  

[16488 rows x 9 columns]

In [14]:
df['label']=l
# df['label']=df[l].apply(lambda x: x.tolist())
df['label'].astype(dtype=str)

0        1
1        6
2        1
3        6
4        5
        ..
16483    2
16484    5
16485    3
16486    1
16487    3
Name: label, Length: 16488, dtype: object

In [15]:
img_filepath=df['filepath']
batch_size=32
# img_filepath.shape
# 

In [30]:
# # pd=df.join([df,train_labels],how='inner',ignore_index = True)
pf=df.set_index('id').join(train_labels.set_index('id'))
# pf['antelope_duiker', 'bird', 'blank', 'civet_genet', 'hog', 'leopard',
#        'monkey_prosimian', 'rodent'].astype('str')
pf


filepath   site  label  antelope_duiker  bird  \
id                                                                           
ZJ000000  train_features/ZJ000000.jpg  S0120      1              0.0   1.0   
ZJ000001  train_features/ZJ000001.jpg  S0069      6              0.0   0.0   
ZJ000002  train_features/ZJ000002.jpg  S0009      1              0.0   1.0   
ZJ000003  train_features/ZJ000003.jpg  S0008      6              0.0   0.0   
ZJ000004  train_features/ZJ000004.jpg  S0036      5              0.0   0.0   
...                               ...    ...    ...              ...   ...   
ZJ016483  train_features/ZJ016483.jpg  S0093      2              0.0   0.0   
ZJ016484  train_features/ZJ016484.jpg  S0043      5              0.0   0.0   
ZJ016485  train_features/ZJ016485.jpg  S0089      3              0.0   0.0   
ZJ016486  train_features/ZJ016486.jpg  S0095      1              0.0   1.0   
ZJ016487  train_features/ZJ016487.jpg  S0021      3              0.0   0.0   

          blank  civet_genet  hog  leopard  monkey_prosimian  rodent  
id                                                                    
ZJ000000    0.0          0.0  0.0      0.0               0.0     0.0  
ZJ000001    0.0          0.0  0.0      0.0               1.0     0.0  
ZJ000002    0.0          0.0  0.0      0.0               0.0     0.0  
ZJ000003    0.0          0.0  0.0      0.0               1.0     0.0  
ZJ000004    0.0          0.0  0.0      1.0               0.0     0.0  
...         ...          ...  ...      ...               ...     ...  
ZJ016483    1.0          0.0  0.0      0.0               0.0     0.0  
ZJ016484    0.0          0.0  0.0      1.0               0.0     0.0  
ZJ016485    0.0          1.0  0.0      0.0               0.0     0.0  
ZJ016486    0.0          0.0  0.0      0.0               0.0     0.0  
ZJ016487    0.0          1.0  0.0      0.0               0.0     0.0  

[16488 rows x 11 columns]

In [31]:
pf.columns

Index(['filepath', 'site', 'label', 'antelope_duiker', 'bird', 'blank',
       'civet_genet', 'hog', 'leopard', 'monkey_prosimian', 'rodent'],
      dtype='object')

In [49]:
d=pf.astype(str,copy=False)
d
d[['path','file']] = d.filepath.str.split("/",expand=True)
d

filepath   site label antelope_duiker bird blank  \
id                                                                              
ZJ000000  train_features/ZJ000000.jpg  S0120     1             0.0  1.0   0.0   
ZJ000001  train_features/ZJ000001.jpg  S0069     6             0.0  0.0   0.0   
ZJ000002  train_features/ZJ000002.jpg  S0009     1             0.0  1.0   0.0   
ZJ000003  train_features/ZJ000003.jpg  S0008     6             0.0  0.0   0.0   
ZJ000004  train_features/ZJ000004.jpg  S0036     5             0.0  0.0   0.0   
...                               ...    ...   ...             ...  ...   ...   
ZJ016483  train_features/ZJ016483.jpg  S0093     2             0.0  0.0   1.0   
ZJ016484  train_features/ZJ016484.jpg  S0043     5             0.0  0.0   0.0   
ZJ016485  train_features/ZJ016485.jpg  S0089     3             0.0  0.0   0.0   
ZJ016486  train_features/ZJ016486.jpg  S0095     1             0.0  1.0   0.0   
ZJ016487  train_features/ZJ016487.jpg  S0021     3             0.0  0.0   0.0   

         civet_genet  hog leopard monkey_prosimian rodent            path  \
id                                                                          
ZJ000000         0.0  0.0     0.0              0.0    0.0  train_features   
ZJ000001         0.0  0.0     0.0              1.0    0.0  train_features   
ZJ000002         0.0  0.0     0.0              0.0    0.0  train_features   
ZJ000003         0.0  0.0     0.0              1.0    0.0  train_features   
ZJ000004         0.0  0.0     1.0              0.0    0.0  train_features   
...              ...  ...     ...              ...    ...             ...   
ZJ016483         0.0  0.0     0.0              0.0    0.0  train_features   
ZJ016484         0.0  0.0     1.0              0.0    0.0  train_features   
ZJ016485         1.0  0.0     0.0              0.0    0.0  train_features   
ZJ016486         0.0  0.0     0.0              0.0    0.0  train_features   
ZJ016487         1.0  0.0     0.0              0.0    0.0  train_features   

                  file  
id                      
ZJ000000  ZJ000000.jpg  
ZJ000001  ZJ000001.jpg  
ZJ000002  ZJ000002.jpg  
ZJ000003  ZJ000003.jpg  
ZJ000004  ZJ000004.jpg  
...                ...  
ZJ016483  ZJ016483.jpg  
ZJ016484  ZJ016484.jpg  
ZJ016485  ZJ016485.jpg  
ZJ016486  ZJ016486.jpg  
ZJ016487  ZJ016487.jpg  

[16488 rows x 13 columns]

Map Image to its label

In [38]:
tf.__version__

'2.9.1'

In [15]:
# # import image
# from tensorflow import keras
# from tensorflow.keras.utils import load_img,img_to_array,array_to_img,to_categorical
# class MyTrainingData(keras.utils.Sequence):
#     def __init__(self, file, labels, batchSize):
#         self.file = file
#         self.label = labels
#         self.batchSize = batchSize
#         self.n_batches = int(len(self.file) / self.batchSize)



#     def on_epoch_end(self):  # it is called after every epoch
# #         self.file, self.label =shuffle(self.file, self.label)
#         for i in range(50):
#             print(self.file[i], self.label[i], 'file-label')


#     def __len__(self):
#         return self.n_batches
    

#     # called after every batch to get new batch or new 32 images and labels
#     def __getitem__(self, idx):
#         # this method calls by fit method with idx ranging from 0 to len(training_exmaples) / batch_size =
#         batchX = self.file[idx*self.batchSize: (idx+1)*self.batchSize]
#         batchY = self.label[idx*self.batchSize: (idx+1)*self.batchSize]
#         imgFiles = [tf.keras.utils.load_img(name, target_size=(224, 224, 3)) for name in batchX]   #loading 32 images
#         imgFiles = [tf.keras.utils.img_to_array(img) for img in imgFiles]   #preprocessing
#         imgFiles = [img / 255 for img in imgFiles] 
#         batchY = to_categorical(batchY, 8)    # 4 represent number of classes (4 in that case)
#         return np.array(imgFiles), np.array(batchY)


In [51]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
train=ImageDataGenerator()
train_gen=train.flow_from_dataframe(d,t,x_col='file',y_col='label',batch_size=32,color_mode='rgb',class_mode='categorical',target_size=(224,224))
# test,x_col='filepath',batch_size=32,class_mode=None,target_size=(224,224)
train_gen.shape

Found 16488 validated image filenames belonging to 8 classes.


AttributeError: 'DataFrameIterator' object has no attribute 'shape'

In [17]:
cd D:/Course/DrivenData Project/Dataset

D:\Course\DrivenData Project\Dataset


In [18]:
# data=MyTrainingData(img_filepath,l,batch_size)

In [19]:
# print(type(data))
# len(data)

<class '__main__.MyTrainingData'>


515

In [20]:
# !pip install pillow

# Model

In [21]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, MaxPool2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.regularizers import l1, l2, l1_l2

In [22]:
model=Sequential()
model.add(Conv2D(60,(3,3),input_shape=(224,224,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(60,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(100,activation='relu',activity_regularizer=l1(0.001)))
model.add(Dense(8))
model.add(Activation('softmax'))

In [23]:
model.compile(loss='binary_crossentropy',optimizer='Adam' ,metrics=['accuracy'])

In [24]:
tf=model.fit(data,epochs=10,verbose=1,shuffle=True)

Epoch 1/10
515/515 [==============================] - 64s 115ms/step - loss: 0.3076 - accuracy: 0.5236
train_features/ZJ000000.jpg 1 file-label
train_features/ZJ000001.jpg 6 file-label
train_features/ZJ000002.jpg 1 file-label
train_features/ZJ000003.jpg 6 file-label
train_features/ZJ000004.jpg 5 file-label
train_features/ZJ000005.jpg 4 file-label
train_features/ZJ000006.jpg 3 file-label
train_features/ZJ000007.jpg 0 file-label
train_features/ZJ000008.jpg 5 file-label
train_features/ZJ000009.jpg 1 file-label
train_features/ZJ000010.jpg 5 file-label
train_features/ZJ000011.jpg 5 file-label
train_features/ZJ000012.jpg 6 file-label
train_features/ZJ000013.jpg 2 file-label
train_features/ZJ000014.jpg 6 file-label
train_features/ZJ000015.jpg 2 file-label
train_features/ZJ000016.jpg 5 file-label
train_features/ZJ000017.jpg 1 file-label
train_features/ZJ000018.jpg 2 file-label
train_features/ZJ000019.jpg 6 file-label
train_features/ZJ000020.jpg 5 file-label
train_features/ZJ000021.jpg 6 file-l

515/515 [==============================] - 59s 114ms/step - loss: 0.1023 - accuracy: 0.8921
train_features/ZJ000000.jpg 1 file-label
train_features/ZJ000001.jpg 6 file-label
train_features/ZJ000002.jpg 1 file-label
train_features/ZJ000003.jpg 6 file-label
train_features/ZJ000004.jpg 5 file-label
train_features/ZJ000005.jpg 4 file-label
train_features/ZJ000006.jpg 3 file-label
train_features/ZJ000007.jpg 0 file-label
train_features/ZJ000008.jpg 5 file-label
train_features/ZJ000009.jpg 1 file-label
train_features/ZJ000010.jpg 5 file-label
train_features/ZJ000011.jpg 5 file-label
train_features/ZJ000012.jpg 6 file-label
train_features/ZJ000013.jpg 2 file-label
train_features/ZJ000014.jpg 6 file-label
train_features/ZJ000015.jpg 2 file-label
train_features/ZJ000016.jpg 5 file-label
train_features/ZJ000017.jpg 1 file-label
train_features/ZJ000018.jpg 2 file-label
train_features/ZJ000019.jpg 6 file-label
train_features/ZJ000020.jpg 5 file-label
train_features/ZJ000021.jpg 6 file-label
train_

515/515 [==============================] - 59s 114ms/step - loss: 0.0637 - accuracy: 0.9425
train_features/ZJ000000.jpg 1 file-label
train_features/ZJ000001.jpg 6 file-label
train_features/ZJ000002.jpg 1 file-label
train_features/ZJ000003.jpg 6 file-label
train_features/ZJ000004.jpg 5 file-label
train_features/ZJ000005.jpg 4 file-label
train_features/ZJ000006.jpg 3 file-label
train_features/ZJ000007.jpg 0 file-label
train_features/ZJ000008.jpg 5 file-label
train_features/ZJ000009.jpg 1 file-label
train_features/ZJ000010.jpg 5 file-label
train_features/ZJ000011.jpg 5 file-label
train_features/ZJ000012.jpg 6 file-label
train_features/ZJ000013.jpg 2 file-label
train_features/ZJ000014.jpg 6 file-label
train_features/ZJ000015.jpg 2 file-label
train_features/ZJ000016.jpg 5 file-label
train_features/ZJ000017.jpg 1 file-label
train_features/ZJ000018.jpg 2 file-label
train_features/ZJ000019.jpg 6 file-label
train_features/ZJ000020.jpg 5 file-label
train_features/ZJ000021.jpg 6 file-label
train_

Evaluation


In [28]:
# tf.History()

AttributeError: 'History' object has no attribute 'History'

In [29]:
model.save("CNN.1")

INFO:tensorflow:Assets written to: CNN.1\assets


INFO:tensorflow:Assets written to: CNN.1\assets


In [ ]:
# import pickle as pk

# with open("cnn-model1.pickle", 'wb') as cnn:
#     pk.dump(model, cnn)
#     cnn.close()

In [ ]:
# import tensorflow as tf

In [ ]:
# import pickle as pk
# with open("C:/Users/Karan/conser-vision/data/pickles/cnn-model1.pickle", 'rb') as sm:
#     model=pk.load(sm)
#     sm.close()

In [30]:
loaded=tensorflow.keras.models.load_model('CNN.1')

In [31]:
test=pd.read_csv('test_features.csv')
test

id                    filepath   site
0     ZJ016488  test_features/ZJ016488.jpg  S0082
1     ZJ016489  test_features/ZJ016489.jpg  S0040
2     ZJ016490  test_features/ZJ016490.jpg  S0040
3     ZJ016491  test_features/ZJ016491.jpg  S0041
4     ZJ016492  test_features/ZJ016492.jpg  S0040
...        ...                         ...    ...
4459  ZJ020947  test_features/ZJ020947.jpg  S0086
4460  ZJ020948  test_features/ZJ020948.jpg  S0152
4461  ZJ020949  test_features/ZJ020949.jpg  S0162
4462  ZJ020950  test_features/ZJ020950.jpg  S0055
4463  ZJ020951  test_features/ZJ020951.jpg  S0114

[4464 rows x 3 columns]

In [32]:

# Test_imgFiles = [tf.keras.utils.load_img(name, target_size=(224, 224, 3)) for name in test['filepath']]

In [33]:
# print(len(Test_imgFiles))
# Test_imgFiles=np.array(Test_imgFiles)
# Test_imgFiles.shape

In [34]:
# Test_imgFiles=[tf.keras.utils.img_to_array(img) for img in Test_imgFiles]
# # y=tf.convert_to_tensor(Test_imgFiles)

In [35]:
# tf.config.experimental.get_memory_info('GPU:0')['current'] / 10**9

In [36]:
# y_pred=model.predict(Test_imgFiles[3])

In [37]:
img_size=(224,224)
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [38]:
def make_gens(batch_size,test_df,img_size):
    t_gen=ImageDataGenerator()
    test_gen=t_gen.flow_from_dataframe(test,x_col='filepath',batch_size=32,class_mode=None,target_size=(224,224))
    test_steps=int(len(test_df)/batch_size)
    return test_gen,test_steps

In [39]:
test_gen,steps=make_gens(32,test,img_size)

Found 4464 validated image filenames.


In [40]:
test_gen[0].shape

(32, 224, 224, 3)

In [41]:
preds=model.predict(test_gen,verbose=1)

140/140 [==============================] - 33s 235ms/step


In [42]:
type(preds)
preds.shape
preds

array([[0.0000000e+00, 0.0000000e+00, 2.4538881e-24, ..., 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [43]:
np.set_printoptions(suppress=True)

In [44]:
preds[1]

array([0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [45]:
# preds_1 = np.array([np.argmax(preds[i, :]) for i in range(preds.shape[0])])

In [46]:
# preds

In [47]:
z_pred=np.zeros_like(preds)
for i in range(preds.shape[0]):
    j=np.argmax(preds[i,:])
    z_pred[i,j]=1
z_pred

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [48]:
final_labels=[]
for i in range(preds.shape[0]):
    final_labels.append(np.argmax(preds[i]))

In [49]:
final_labels=np.array(final_labels)

In [118]:
final_labels[0]

3

In [88]:
pp=np.unique(final_labels)

In [87]:
classes

Index(['antelope_duiker', 'bird', 'blank', 'civet_genet', 'hog', 'leopard',
       'monkey_prosimian', 'rodent'],
      dtype='object')

In [90]:
c_l=dict()
for i in pp:
    c_l[i]=classes[i]
c_l

{0: 'antelope_duiker',
 1: 'bird',
 2: 'blank',
 3: 'civet_genet',
 4: 'hog',
 5: 'leopard',
 6: 'monkey_prosimian',
 7: 'rodent'}

In [91]:
pp=np.unique(final_labels,return_counts=True)

In [93]:
pp[0]

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [94]:
for i in range(pp[0].shape[0]):
    pp[0][i]=np.where(pp[0,i] in c_l.keys(),
                      c_l[i],
                      0)

TypeError: tuple indices must be integers or slices, not tuple

In [51]:
sub=pd.read_csv('submission_format.csv')
sub=sub.iloc[:,1:].to_numpy()
sub[0]

array([0.04823279, 0.18918532, 0.04491418, 0.19958797, 0.10611783,
       0.13291451, 0.16640995, 0.11263745])

In [52]:
soc=np.zeros_like(sub)
for i in range(sub.shape[0]):
    j=np.argmax(sub[i,:])
    soc[i,j]=1
soc
# k=np.argmax(sub[0,:])
# k

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(z_pred, soc)

ModuleNotFoundError: No module named 'sklearn'

In [54]:
z_pred

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [55]:
soc

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [56]:
np.savetxt('1',z_pred,delimiter=',')

In [ ]:
np.