In [1]:
import numpy as np
import pandas as pd
import cv2

In [4]:
# root_path = "/Users/devasenan/Documents/conser-vision/data/"
root_path = "C:/Users/devas/Documents/projects/conser-vision/data/"

In [5]:
train_features = pd.read_csv(root_path+"train_features.csv")
train_features.head()

id                     filepath   site
0  ZJ000000  train_features/ZJ000000.jpg  S0120
1  ZJ000001  train_features/ZJ000001.jpg  S0069
2  ZJ000002  train_features/ZJ000002.jpg  S0009
3  ZJ000003  train_features/ZJ000003.jpg  S0008
4  ZJ000004  train_features/ZJ000004.jpg  S0036

In [28]:
train_features.iloc[1, :]

id                             ZJ000001
filepath    train_features/ZJ000001.jpg
site                              S0069
Name: 1, dtype: object

In [7]:
x_train = []

for image in train_features.iloc[:, 1]:
    img=cv2.imread(root_path+image)
    img = cv2.resize(img, (335, 335))
    x_train.append(img)

train_x = np.array(x_train)

In [8]:
train_x

array([[[[139, 139, 139],
         [141, 141, 141],
         [147, 147, 147],
         ...,
         [108, 108, 108],
         [108, 108, 108],
         [107, 107, 107]],

        [[140, 140, 140],
         [141, 141, 141],
         [148, 148, 148],
         ...,
         [105, 105, 105],
         [107, 107, 107],
         [110, 110, 110]],

        [[141, 141, 141],
         [143, 143, 143],
         [149, 149, 149],
         ...,
         [101, 101, 101],
         [105, 105, 105],
         [110, 110, 110]],

        ...,

        [[ 81, 127, 212],
         [ 47,  94, 178],
         [ 54, 101, 185],
         ...,
         [ 69,  69,  69],
         [ 91,  91,  91],
         [251, 251, 251]],

        [[ 65, 119, 220],
         [ 44, 102, 207],
         [ 38, 101, 209],
         ...,
         [171, 171, 171],
         [162, 162, 162],
         [254, 254, 254]],

        [[ 61, 118, 224],
         [ 38, 101, 214],
         [ 29,  97, 218],
         ...,
         [251, 251, 251],
        

In [9]:
nsamples, nx, ny, nrgb = train_x.shape
train_x = train_x.reshape((nsamples,nx*ny*nrgb))

In [10]:
train_x

array([[139, 139, 139, ..., 246, 246, 246],
       [132, 132, 132, ..., 248, 248, 248],
       [150, 150, 150, ..., 251, 251, 251],
       ...,
       [137, 137, 137, ..., 241, 241, 241],
       [ 16,  16,  16, ...,  31,  31,  31],
       [ 87,  88,  68, ..., 110,  94,  88]], dtype=uint8)

In [18]:
train_y = pd.read_csv(root_path+"train_labels.csv")
train_y = train_y.iloc[:25, 1:]

In [12]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

In [19]:
train_x.shape

(25, 336675)

In [20]:
train_y.shape

(25, 8)

In [21]:
model.fit(train_x,train_y)

RandomForestClassifier()

In [23]:
model

RandomForestClassifier()

In [25]:
train_x[1]

array([132, 132, 132, ..., 248, 248, 248], dtype=uint8)

In [29]:
y_pred = model.predict([train_x[30]])
y_pred


IndexError: index 30 is out of bounds for axis 0 with size 25

In [ ]:

accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test))

confusion_matrix(y_pred,y_test)